name: 'Build AUR Package'
branding:
  icon: user-check
  color: gray-dark
inputs:
  pkgdir:
    description: 'AUR repository name to build'
    required: true
  pkgname:
    description: 'AUR package / repository name'
    required: true
  rebuild_current:
    description: 'Rebuild current package version for dependency ABI changes'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pkgdir }}
    - ${{ inputs.pkgname }}
    - ${{ inputs.rebuild_current }}
